package io.github.yuroyami.kiteffmpeg.wasm

/*
 * GENERATED by scripts/wasm-report-offsets.sh from offsetof(). Do not edit.
 *
 * The byte layout of `kc_ffmpeg_report`, which the web backend reads out of the codec module's
 * memory because JavaScript cannot see a C struct. A wrong number here reads the neighbouring
 * field and answers something plausible, which is why these are compiler output and are checked.
 */
internal object ReportLayout {
    const val status: Int = 0
    const val bypassed: Int = 4
    const val abiMajor: Int = 8
    const val abiMinor: Int = 12
    const val headerMajor: Int = 16
    const val headerMinor: Int = 40
    const val headerMicro: Int = 64
    const val runtimeMajor: Int = 88
    const val runtimeMinor: Int = 112
    const val runtimeMicro: Int = 136
    const val verdict: Int = 160
    const val configurationAgrees: Int = 184
    const val configurationDisagreedCount: Int = 188
    const val configurationDisagreed: Int = 192
    const val buildFfmpegRef: Int = 320
    const val buildLicenseFlavour: Int = 352
    const val buildProvisioningDir: Int = 384
    const val runtimeVersionInfo: Int = 896
    const val runtimeLicense: Int = 960
    const val provisioning: Int = 1024
    const val LIBRARY_COUNT: Int = 6
    const val TEXT_REF: Int = 32
    const val TEXT_NAME: Int = 64
    const val TEXT_LIST: Int = 128
    const val TEXT_PATH: Int = 512
    const val TEXT_SENTENCE: Int = 1152
    const val SIZE_OF: Int = 2176
}
