package io.github.yuroyami.kiteffmpeg

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * What a Matroska file says about its segment, its editions and their chapters reaches
 * [MediaSource.matroska] (#173), from files mkvmerge wrote and through both kinds of open.
 *
 * FFmpeg reads one edition as plain chapters and none of the rest, so the facts come from the
 * segment's Info and Chapters payloads, which the FFmpeg patch `0014` exports from the demuxer. A
 * tree built before that patch exports nothing and reads `matroska` as null, so this test fails on
 * it.
 */
class MatroskaSegmentContractTest {

    private fun segmentOfFile(bytes: ByteArray, sha256: String): MatroskaSegment? =
        MediaSource.open(materializeContractMedia(bytes, sha256)).use { it.matroska }

    /** Sixteen bytes counting up from [first], as the fixtures' UIDs are written. */
    private fun run(first: Int): String = (first until first + 16).joinToString("") { it.toString(16).padStart(2, '0') }

    @Test
    fun anEpisodeNamesItsSegmentItsNeighboursAndItsFamily() {
        val segment = assertNotNull(segmentOfFile(EpisodeMatroska.bytes, EpisodeMatroska.sha256))
        assertEquals(run(0xB0), segment.uid)
        assertEquals("episode.mkv", segment.filename)
        assertEquals(run(0x61).take(16).repeat(2), segment.previousUid)
        assertEquals("previous.mkv", segment.previousFilename)
        assertEquals(run(0x71).take(16).repeat(2), segment.nextUid)
        assertEquals("next.mkv", segment.nextFilename)
        assertEquals(listOf(run(0x51)), segment.families)
    }

    @Test
    fun anEpisodeOrderedEditionLinksItsOpeningAndEndingFromOtherSegments() {
        val segment = assertNotNull(segmentOfFile(EpisodeMatroska.bytes, EpisodeMatroska.sha256))
        val (episode, hidden) = segment.editions
        assertEquals(episode, segment.defaultEdition)
        assertEquals(3001L, episode.uid)
        assertTrue(episode.isDefault)
        assertTrue(episode.isOrdered)
        assertFalse(episode.isHidden)
        assertEquals(listOf(MatroskaName("Episode", listOf("en"), emptyList())), episode.names)

        val (opening, partA, ending, preview) = episode.chapters
        assertEquals(31L, opening.uid)
        assertEquals(run(0x31), opening.segmentUid)
        assertNull(opening.segmentEditionUid)
        assertEquals(0L to 90_000_000_000L, opening.startNanos to opening.endNanos)
        assertEquals(MatroskaSkipType.OpeningCredits, opening.skipType)
        assertEquals(listOf(MatroskaName("Opening", listOf("en"), emptyList())), opening.names)

        assertEquals(32L, partA.uid)
        assertNull(partA.segmentUid)
        assertNull(partA.skipType)
        assertEquals(listOf(321L, 322L), partA.chapters.map { it.uid })
        val sceneTwo = partA.chapters[1]
        assertEquals("scene-2", sceneTwo.stringUid)
        assertEquals(1_000_000_000L to 3_000_000_000L, sceneTwo.startNanos to sceneTwo.endNanos)
        assertEquals(listOf(MatroskaName("Scène deux", listOf("fr-CA"), emptyList())), sceneTwo.names)

        assertEquals(33L, ending.uid)
        assertEquals(run(0x41), ending.segmentUid)
        assertEquals(9001L, ending.segmentEditionUid)
        assertEquals(MatroskaSkipType.EndCredits, ending.skipType)

        assertEquals(34L, preview.uid)
        assertEquals(MatroskaSkipType.NextPreview, preview.skipType)

        assertEquals(listOf(31L, 321L, 322L, 33L, 34L), episode.playlist?.map { it.uid })

        assertEquals(3002L, hidden.uid)
        assertTrue(hidden.isHidden)
        assertFalse(hidden.isDefault)
        assertFalse(hidden.isOrdered)
        assertNull(hidden.playlist)
        assertNull(hidden.chapters.single().endNanos)
    }

    @Test
    fun thePlainChapterListStaysTheDefaultEditionsOwnTopLevelChapters() {
        MediaSource.open(materializeContractMedia(EpisodeMatroska.bytes, EpisodeMatroska.sha256)).use { source ->
            assertEquals(listOf(32L to "Part A", 34L to "Next time"), source.chapters.map { it.id to it.title })
        }
    }

    @Test
    fun aByteSourceReadsTheSameSegmentWhetherOrNotItCanSeek() {
        val fromFile = assertNotNull(segmentOfFile(EpisodeMatroska.bytes, EpisodeMatroska.sha256))
        for (seekable in listOf(true, false)) {
            val fromBytes = MediaSource.open(BytesSource(EpisodeMatroska.bytes, seekable)).use { it.matroska }
            assertEquals(fromFile, fromBytes, "seekable = $seekable")
        }
    }

    @Test
    fun theEditionsFileReadsItsLinkedHiddenAndDisabledChapters() {
        val segment = assertNotNull(segmentOfFile(EditionsMatroska.bytes, EditionsMatroska.sha256))
        assertEquals(run(0xA0), segment.uid)
        assertNull(segment.previousUid)
        assertEquals(emptyList(), segment.families)
        val (theatrical, extended) = segment.editions
        assertEquals(listOf(11L, 12L), theatrical.chapters.map { it.uid })
        assertNull(theatrical.playlist)
        assertEquals(extended, segment.defaultEdition)
        val chapters = extended.chapters
        assertEquals(listOf(21L, 22L, 23L, 24L, 25L, 26L), chapters.map { it.uid })
        assertEquals(listOf(false, true, false, false, false, false), chapters.map { it.isHidden })
        assertEquals(listOf(true, true, false, true, true, true), chapters.map { it.isEnabled })
        // 25 names this file's own UID, which reads as no link.
        assertEquals(listOf(null, null, null, run(0x01), null, null), chapters.map { it.segmentUid })
        assertEquals(listOf(21L, 22L, 24L, 25L, 26L), extended.playlist?.map { it.uid })
    }

    @Test
    fun aSourceThatIsNotMatroskaHasNoSegment() {
        MediaSource.open(materializeContractMedia(ContractMedia.bytes, ContractMedia.sha256)).use {
            assertNull(it.matroska)
        }
    }

    private class BytesSource(private val bytes: ByteArray, override val seekable: Boolean) : MediaByteSource {
        private var position = 0
        override val size: Long? get() = if (seekable) bytes.size.toLong() else null

        override fun read(into: ByteArray, offset: Int, length: Int): Int {
            if (position >= bytes.size) return -1
            val count = minOf(length, bytes.size - position)
            bytes.copyInto(into, offset, position, position + count)
            position += count
            return count
        }

        override fun seek(position: Long) {
            this.position = position.toInt()
        }

        override fun close() {}
    }
}

/**
 * One six second SRT cue in Matroska, written by `mkvmerge --deterministic 173` with the segment
 * UID b0 b1 ... bf, the previous segment 61 ... 68 61 ... 68 and the next 71 ... 78 71 ... 78, the
 * family 51 ... 60, and the file names episode.mkv, previous.mkv and next.mkv. Its first edition,
 * 3001 "Episode", is flagged default and ordered and plays: 31 "Opening", 0 to 90 s of the segment
 * 31 ... 40, skip type opening credits; 32 "Part A", 0 to 3 s of this file, holding 321 "Scene one"
 * and 322 "Scène deux" (string UID scene-2, fr-CA); 33 "Ending", the whole edition 9001 of the
 * segment 41 ... 50, skip type end credits; and 34 "Next time", 3 to 6 s, skip type preview of the
 * next episode. Its second, 3002, is hidden and holds one chapter, 41, with no end. mkvmerge adds a
 * BCP 47 tag to every chapter name.
 */
private object EpisodeMatroska {
    const val sha256: String = "02529426b2716e9162f133d7f459676bfc35962870dd1992c0f5c6e1d00a7b3a"

    val bytes: ByteArray by lazy {
        decodeBase64(DATA.filterNot { it.isWhitespace() }).also { decoded ->
            check(decoded.size == 6322) { "EpisodeMatroska fixture size changed: ${decoded.size}" }
            check(sha256Hex(decoded) == sha256) { "EpisodeMatroska fixture digest changed" }
        }
    }

    private val DATA: String = """
GkXfo6NChoEBQveBAULygQRC84EIQoKIbWF0cm9za2FCh4EFQoWBARhTgGcBAAAAAAAYfhFNm3TLTbuMU6uEFUmpZlOsghADTbuM
U6uEFlSua1OsghDnTbuMU6uEHFO7a1OsghdYTbuMU6uEElTDZ1OsghdyTbuMU6uEEEOncFOsghVF7E+wAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmQN4q17GDD0JATYCjbGliZWJtbCB2MS40LjUgKyBsaWJtYXRyb3NrYSB2MS43
LjFXQatta3ZtZXJnZSB2ODIuMCAoJ0knbSBUaGUgUHJlc2lkZW50JykgNjQtYml0RImIQLdwAAAAAABzpJCwsbKztLW2t7i5uru8
vb6/RESQUVJTVFVWV1hZWltcXV5fYDy5I5BhYmNkZWZnaGFiY2RlZmdoPrkjkHFyc3R1dnd4cXJzdHV2d3hzhItlcGlzb2RlLm1r
dj6Du4huZXh0Lm1rdjyDq4xwcmV2aW91cy5ta3YWVK5rsa6v14EBc8WICEqmDn5OzSODgRGcgQAitZyDdW5khotTX1RFWFQvVVRG
OCK1nYN1bmTsRCUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBDp3BBjUW5QWBFvIILuUXbgQFF3YEBRSCPRSGHRXBpc29kZUXkgmVutrtzxIEfkYEAkoUU
9GsEAG5nkDEyMzQ1Njc4OTo7PD0+P0BFiIEBgJSFh09wZW5pbmdDfINlbmdDfYJlbrZAkXPEgSCRgQCShLLQXgCAk4WGUGFydCBB
Q3yDZW5nQ32CZW62rnPEggFBkYEAkoQ7msoAgJ6FiVNjZW5lIG9uZUN8g2VuZ0N+gnVzQ32FZW4tVVO2vXPEggFCVlSHc2NlbmUt
MpGEO5rKAJKEstBeAICghYtTY8OobmUgZGV1eEN8g2ZyZUN+gmNhQ32FZnItQ0G2v3PEgSGRgQCShRT0awQAbmeQQUJDREVGR0hJ
SktMTU5PUG68giMpRYiBAoCThYZFbmRpbmdDfINlbmdDfYJlbratc8SBIpGEstBeAJKFAWWgvABFiIEEgJaFiU5leHQgdGltZUN8
g2VuZ0N9gmVuRbmmRbyCC7pFvYEBtptzxIEpkYEAgJKFhVN0YXJ0Q3yDZW5nQ32CZW7s5QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAH0O2dZTngQCgj6GJgQAAAEhlbGxvm4IXcBxTu2uVu5OzgQC3jveBAfGCFz/wgQOyghdwElTDZ0EGc3NBAmPAi2PFiAhKpg5+
Ts0jZ8iKRaODQlBTRIeBNmfIoEWjiERVUkFUSU9ORIeSMDA6MDA6MDYuMDAwMDAwMDAwZ8iXRaOQTlVNQkVSX09GX0ZSQU1FU0SH
gTFnyJZFo49OVU1CRVJfT0ZfQllURVNEh4E1Z8jIRaOXX1NUQVRJU1RJQ1NfV1JJVElOR19BUFBEh6tta3ZtZXJnZSB2ODIuMCAo
J0knbSBUaGUgUHJlc2lkZW50JykgNjQtYml0Z8jDRaOQX1NUQVRJU1RJQ1NfVEFHU0SHrUJQUyBEVVJBVElPTiBOVU1CRVJfT0Zf
RlJBTUVTIE5VTUJFUl9PRl9CWVRFUw==
"""
}
