package io.github.yuroyami.kiteffmpeg.wasm

/*
 * GENERATED by scripts/wasm-report-offsets.sh from offsetof(). Do not edit.
 *
 * The byte layout of `kc_io_opener`, which the web backend writes into the codec module's memory
 * for a nested opener. A wrong number here stores a callback in the neighbouring field, which is
 * why these are compiler output and are checked.
 */
internal object OpenerLayout {
    const val opaque: Int = 0
    const val openFn: Int = 4
    const val readFn: Int = 8
    const val seekFn: Int = 12
    const val closeFn: Int = 16
    const val SIZE_OF: Int = 20
}
