#!/usr/bin/env bash
# Generates (or checks) the byte layouts of `kc_ffmpeg_report` and `kc_io_opener` for the web
# binding.
#
# JavaScript sees the codec's memory as a flat buffer, so every struct field needs an offset. Those
# belong to the compiler, not to a human with a calculator: a wrong offset reads the NEIGHBOURING
# field and returns a plausible number instead of failing. So they are emitted by `offsetof` and
# committed, and this script re-derives them and refuses a mismatch.
#
#   ./scripts/wasm-report-offsets.sh            # check the committed files, fail on drift
#   ./scripts/wasm-report-offsets.sh --write    # regenerate them after a deliberate struct change
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LAYOUTS="$ROOT/kiteffmpeg/src/wasmJsMain/kotlin/io/github/yuroyami/kiteffmpeg/wasm"
MODE="${1:-check}"
command -v emcc >/dev/null || { echo "emcc is not on PATH" >&2; exit 1; }

WORK=$(mktemp -d); trap 'rm -rf "$WORK"' EXIT
emcc -O0 -I "$ROOT/native/kitecodec-c/include" \
  "$ROOT/native/kitecodec-c/probe/report_offsets.c" -o "$WORK/offsets.js" >/dev/null 2>&1
node "$WORK/offsets.js" > "$WORK/offsets.json"
emcc -O0 -I "$ROOT/native/kitecodec-c/include" \
  "$ROOT/native/kitecodec-c/probe/opener_offsets.c" -o "$WORK/opener.js" >/dev/null 2>&1
node "$WORK/opener.js" > "$WORK/opener.json"

python3 - "$WORK/offsets.json" "$WORK/ReportLayout.kt" <<'PY'
import json, sys
o = json.load(open(sys.argv[1]))
lines = [
 "package io.github.yuroyami.kiteffmpeg.wasm",
 "",
 "/*",
 " * GENERATED by scripts/wasm-report-offsets.sh from offsetof(). Do not edit.",
 " *",
 " * The byte layout of `kc_ffmpeg_report`, which the web backend reads out of the codec module's",
 " * memory because JavaScript cannot see a C struct. A wrong number here reads the neighbouring",
 " * field and answers something plausible, which is why these are compiler output and are checked.",
 " */",
 "internal object ReportLayout {",
]
order = ["status","bypassed","abi_major","abi_minor","header_major","header_minor","header_micro",
         "runtime_major","runtime_minor","runtime_micro","verdict","configuration_agrees",
         "configuration_disagreed_count","configuration_disagreed","build_ffmpeg_ref",
         "build_license_flavour","build_provisioning_dir","runtime_version_info",
         "runtime_license","provisioning"]
def camel(s):
    head, *rest = s.split("_")
    return head + "".join(w.capitalize() for w in rest)
for k in order:
    lines.append("    const val %s: Int = %d" % (camel(k), o[k]))
for k in ["LIBRARY_COUNT","TEXT_REF","TEXT_NAME","TEXT_LIST","TEXT_PATH","TEXT_SENTENCE"]:
    lines.append("    const val %s: Int = %d" % (camel(k.lower()).upper() if False else k, o[k]))
lines.append("    const val SIZE_OF: Int = %d" % o["sizeof"])
lines.append("}")
open(sys.argv[2], "w").write("\n".join(lines) + "\n")
PY

python3 - "$WORK/opener.json" "$WORK/OpenerLayout.kt" <<'PY2'
import json, sys
o = json.load(open(sys.argv[1]))
lines = [
 "package io.github.yuroyami.kiteffmpeg.wasm",
 "",
 "/*",
 " * GENERATED by scripts/wasm-report-offsets.sh from offsetof(). Do not edit.",
 " *",
 " * The byte layout of `kc_io_opener`, which the web backend writes into the codec module's memory",
 " * for a nested opener. A wrong number here stores a callback in the neighbouring field, which is",
 " * why these are compiler output and are checked.",
 " */",
 "internal object OpenerLayout {",
]
def camel(s):
    head, *rest = s.split("_")
    return head + "".join(w.capitalize() for w in rest)
for k in ["opaque", "open_fn", "read_fn", "seek_fn", "close_fn", "location_fn"]:
    lines.append("    const val %s: Int = %d" % (camel(k), o[k]))
lines.append("    const val SIZE_OF: Int = %d" % o["sizeof"])
lines.append("}")
open(sys.argv[2], "w").write("\n".join(lines) + "\n")
PY2

if [ "$MODE" = "--write" ]; then
  mkdir -p "$LAYOUTS"
  for layout in ReportLayout OpenerLayout; do
    cp "$WORK/$layout.kt" "$LAYOUTS/$layout.kt"
    echo "wrote $LAYOUTS/$layout.kt"
  done
  exit 0
fi
failed=0
for layout in ReportLayout OpenerLayout; do
  if [ ! -f "$LAYOUTS/$layout.kt" ]; then
    echo "missing $LAYOUTS/$layout.kt. Run $0 --write" >&2
    failed=1
  elif ! diff -u "$LAYOUTS/$layout.kt" "$WORK/$layout.kt"; then
    echo "wasm-report-offsets.sh: FAIL, the struct behind $layout moved. Re-run with --write and say why." >&2
    failed=1
  fi
done
[ "$failed" = 0 ] || exit 1
echo "wasm-report-offsets.sh: PASS, the committed layouts match offsetof()"
