package io.github.yuroyami.kiteffmpeg

import kotlin.math.abs
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * A Dolby Vision profile 5 clip and the picture its composition should give, shared by the
 * backend contract test and the web test.
 *
 * scripts/dolby-vision-fixture/make-fixture.sh makes both. The clip is two 32x24 frames in MP4:
 * a 10-bit HEVC base layer of smooth ramps in full range, with an RPU on each frame that reshapes
 * luma through three polynomial pieces and chroma through third-order MMR. The two RPUs differ in
 * their luma curve and their level 1 brightness. The expected picture is libplacebo's composition
 * of the same clip, an implementation independent of this one, in the layout KiteFFmpeg writes:
 * 10-bit Y'CbCr 4:2:0, limited range, chroma sited left, Y then Cb then Cr for each frame.
 */
internal object DolbyVisionFixtures {
    const val WIDTH: Int = 32
    const val HEIGHT: Int = 24
    const val FRAMES: Int = 2

    /** The source's range that both RPUs declare, as 12-bit PQ codes. */
    const val SOURCE_MIN_PQ: Int = 7
    const val SOURCE_MAX_PQ: Int = 3079

    /** Each frame's level 1 brightness: minimum, average and maximum, as 12-bit PQ codes. */
    val SCENE_BRIGHTNESS: List<DolbyVisionBrightness> = listOf(
        DolbyVisionBrightness(minPq = 0, averagePq = 819, maxPq = 2081),
        DolbyVisionBrightness(minPq = 7, averagePq = 1365, maxPq = 3079),
    )

    const val CLIP_SHA256: String = "0cec210a4c42ac558e83f8f054ab20deaf87873bee8ae99d36286f3f78603d32"

    val CLIP: ByteArray by lazy {
        decodeBase64(CLIP_DATA.filterNot { it.isWhitespace() }).also {
            check(it.size == 1878) { "Dolby Vision clip size changed: ${it.size}" }
            check(sha256Hex(it) == CLIP_SHA256) { "Dolby Vision clip digest changed" }
        }
    }

    /** The expected picture of every frame, as little-endian 16-bit samples. */
    val EXPECTED: ShortArray by lazy {
        val bytes = decodeBase64(EXPECTED_DATA.filterNot { it.isWhitespace() })
        check(bytes.size == 4608) { "Dolby Vision expected picture size changed: ${bytes.size}" }
        check(sha256Hex(bytes) == "915e9c38f429eb17dd6c0d1528982babc12fafc09a2ec268a7a69fdbdf5299d4") { "Dolby Vision expected picture digest changed" }
        ShortArray(bytes.size / 2) { ((bytes[2 * it].toInt() and 0xFF) or (bytes[2 * it + 1].toInt() shl 8)).toShort() }
    }

    /**
     * The most a composed sample may differ from [EXPECTED], in codes. Measured at 1 on the first
     * frame and 4 on the second: the two implementations upsample chroma with different filters,
     * and where a channel of a saturated colour sits near zero light, the foot of the PQ curve
     * turns that into a few codes.
     */
    const val TOLERANCE: Int = 4

    /** The most the mean difference of one plane of one frame may be, in codes. Measured at 0.47. */
    const val MEAN_TOLERANCE: Double = 0.75

    /** Holds frame [index]'s composed planes to libplacebo's, sample by sample and plane by plane. */
    fun assertMatchesExpected(index: Int, planes: ByteArray) {
        val w = WIDTH
        val h = HEIGHT
        val lumaSamples = w * h
        val chromaSamples = (w + 1) / 2 * ((h + 1) / 2)
        val perFrame = lumaSamples + 2 * chromaSamples
        assertEquals(perFrame * 2, planes.size, "the composed planes of frame $index")
        val expected = EXPECTED
        listOf("Y" to (0 until lumaSamples), "Cb" to (lumaSamples until lumaSamples + chromaSamples), "Cr" to (lumaSamples + chromaSamples until perFrame))
            .forEach { (plane, range) ->
                var total = 0L
                for (i in range) {
                    val got = (planes[2 * i].toInt() and 0xFF) or ((planes[2 * i + 1].toInt() and 0xFF) shl 8)
                    val want = expected[index * perFrame + i].toInt()
                    val difference = abs(got - want)
                    assertTrue(
                        difference <= TOLERANCE,
                        "frame $index $plane sample ${i - range.first}: composed $got, libplacebo $want",
                    )
                    total += difference
                }
                val mean = total.toDouble() / (range.last - range.first + 1)
                assertTrue(mean <= MEAN_TOLERANCE, "frame $index $plane: mean difference $mean")
            }
    }

    private val CLIP_DATA: String = """
AAAAFGZ0eXBpc280AAAAAWlzbzQAAAOrbW9vdgAAAGxtdmhkAAAAAObnDvDm5w7wAAACWAAAADIAAQAAAQAAAAAAAAAAAAAAAAEA
AAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAr90cmFrAAAAXHRr
aGQAAAAH5ucO8ObnDvAAAAABAAAAAAAAADIAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABA
AAAAACAAAAAYAAAAAAJbbWRpYQAAACBtZGhkAAAAAObnDvDm5w7wAAAAGAAAAAJVxAAAAAAAVWhkbHIAAAAAAAAAAHZpZGUAAAAA
AAAAAAAAAABoZXZjOmR2cD01OmZwcz0yNEBHUEFDMi4yLjEtcmV2Mi4yLjErZGZzZzEtMy4xYnVpbGQyAAAAAd5taW5mAAAAFHZt
aGQAAAABAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAGec3RibAAAAR5zdHNkAAAAAAAAAAEA
AAEOZHZoMQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAgABgASAAAAEgAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAABj//wAAAHRodmNDAQIgAAAAkAAAAAAAHvAA/f36+gAADwOgAAEAGEABDAH//wIgAAADAJAAAAMAAAMAHpWYCaEAAQAo
QgEBAiAAAAMAkAAAAwAAAwAeoEIZNllZqvK8BbAgAAADACAAAAMDAaIAAQAGRAHBc9CJAAAAIGR2Y0MBAAoNAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAQcGFzcAAAAAEAAAABAAAAFGJ0cnQAAAGzAAE6oAABOqAAAAAYc3R0cwAAAAAAAAABAAAAAgAAAAEAAAAUc3Rz
cwAAAAAAAAABAAAAAQAAABxzdHNjAAAAAAAAAAEAAAABAAAAAgAAAAEAAAAcc3RzegAAAAAAAAAAAAAAAgAAAbMAAAGUAAAAFHN0
Y28AAAAAAAAAAQAAA8cAAAB4dWR0YQAAAHBtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABtZGlyAAAAAAAAAAAAAAAAAAAAAENpbHN0
AAAAO6l0b28AAAAzZGF0YQAAAAEAAAAAR1BBQy0yLjIuMS1yZXYyLjIuMStkZnNnMS0zLjFidWlsZDIAAANPbWRhdAAAAGUoAa8N
4FIycUgv5mjzm6P18eWEsAXx+ZOJJies4L+sH4/WqNMhs8Q1BAQM5J/dW4lptUDKyIVEjK8FG34CgHPZijihgPs1Ipp1/+DrdzF3
HkC55BmuWERegeobdUOwOuS4Mnb/gAAAAUZ8ARkICQBAYbZQbsAEAYBf4Af/AD/+oAAAEMzM15mZmqCj1z9cKR+Zmap+uFIQKPXI
KPXFQKPXQUeufMzNQKPXP4Ue0FHrkCj1z/XClAo9dCj1xAAABAAABAo9dAAABAAABAAAAwP64UkAAAMBAAADAQAAAwEAAAMBAAAD
AKf64Un9cKSBR65Ao9cgo9cfwo9oAAAIFHroAAAIAAAH8KPaBR66AAADAgAAAwIAAAMCAAADAgAAAwIKPXIAAAMCAAADAgAAAwIA
AAMDRAAAY+DSJAAfi2CIZAAAIX1K4AAAAwABAAADAAEAAAMACFc/1H/Uf9RoVz/Uf9R/1GhXP//gAAADAAADAAADAAyEAfAcKiAw
CABBCZmAgFAAAAMAAAMAAAMBIMB9AAAgdeAyBTAcAEAEAAIJAH/AAEULAQAAAwDHmi+dgAAAAEYCAdAJfhDGG8CVC7fuz9njIhn7
H5NxDc48OJMKFTAnDKrrMW0Z8YZC/aPxaZBu7plpE4GFWWky9CIYbq7XdRwp5RkVE/bYAAABRnwBGQgJAEBhtlBuwAQBgF/gB/8A
P/6gAAAQZmZnzMzOoFHrv64Un8KPan9cKRAUeugUeuVAo9dBR658zM1Ao9c/hR7QUeuQKPXP9cKUCj10KPXEAAAEAAAECj10AAAE
AAAEAAADA/rhSQAAAwEAAAMBAAADAQAAAwEAAAMAp/rhSf1wpIFHrkCj1yCj1x/Cj2gAAAgUeugAAAgAAAfwo9oFHroAAAMCAAAD
AgAAAwIAAAMCAAADAgo9cgAAAwIAAAMCAAADAgAAAwNEAABj4NIkAB+LYIhkAAAhfUrgAAADAAEAAAMAAQAAAwAIVz/Uf9R/1GhX
P9R/1H/UaFc//+AAAAMAAAMAAAMADIQB8BwqIDAIA+A6qoCAUAAAAwAAAwAAAwEgwH0AACB14DIFMBwAQAQAAgkAf8AARQsBAAAD
AAQvG/mAAAAASGZyZWVJc29NZWRpYSBGaWxlIFByb2R1Y2VkIHdpdGggR1BBQyAyLjIuMS1yZXYyLjIuMStkZnNnMS0zLjFidWls
ZDIA
"""

    private val EXPECTED_DATA: String = """
gQCYALIAyQDgAPkAEAEmAT0BUgFpAYIBmAGuAcYB3AH0AQkCIQI2AkoCWwJzAooCpAK7AtQC7wIHAx4DOQNPA4cAngC4AM8A5gD+
ABYBKwFCAVcBbgGHAZ0BtAHMAeEB+gEOAiYCOwJQAmICegKRAqoCwQLaAvYCDQMlAz8DVgOQAKcAwADXAO0ABwEdATIBSQFfAXUB
jgGlAboB0wHoAQECFgItAkICWAJqAoICmgKzAsoC4wL9AhUDLgNHA14DlwCtAMcA3QD0AA0BJAE4AU8BZQF7AZQBqgHAAdgB7gEG
AhoCMgJGAlwCbwKHAp4CuALPAugCAwMaAzMDTQNkA5wAsgDMAOIA+AASAScBPAFSAWgBfwGYAa4BxAHcAfIBCQIdAjYCSgJZAnMC
iwKiArsC0wLsAgcDHwM3A1EDaAOeALQAzQDkAPoAEwEoAT0BVAFqAYABmQGvAcUB3gHyAQsCIAI3AkwCWwJ1Ao0CpAK+AtUC7gIJ
AyEDOQNUA2oDnQC0AM0A4wD5ABIBJwE8AVMBaQF/AZgBrgHEAd0B8gEKAh4CNgJKAloCdAKMAqMCvQLVAu0CCAMgAzgDUgNpA5sA
sQDKAOEA9wAPASYBOgFRAWYBfQGVAawBwgHaAe8BBgIbAjICRwJVAnACiAKfArkC0ALoAgQDHAM0A04DZQOVAKwAxQDbAPIACgEg
ATUBSwFhAXgBkAGnAb0B1QHqAQECFQItAkECUAJqAoICmQKzAsoC4wL+AhYDLgNIA18DjQCjALwA0wDpAAEBGAEtAUMBWQFwAYgB
nwG1Ac0B4gH6AQ8CJgI7Ak8CYwJ8ApMCrALDAtsC9wIPAycDQQNYA4IAmQCyAMkA3wD4AA8BIwE7AVABZgGAAZYBrAHFAdoB8gEH
Ah4CMgJHAloCcgKJAqMCugLTAu4CBgMeAzcDTwN4AJAAqQDAANYA7wAGARsBMgFHAV4BdwGOAaQBvQHSAegB/QEUAikCPgJQAmgC
fwKYAq8CyALjAvsCEwMuA0QDbgCFAJ4AtgDNAOYA/QASASkBPgFWAW8BhQGcAbQBygHgAfUBDAIiAjYCRwJeAnUCjwKnAr8C2gLz
AgoDJQM7A2IAewCVAK0AwwDcAPQACgEhATYBTQFmAX0BlAGsAcEB2QHuAQUCGgIvAkUCVwJuAocCngK3AtEC6gICAxwDMgNZAHIA
jQCkALsA1QDrAAIBGgEvAUYBXwF1AYwBpAG6AdIB5wH+ARMCKAI/Ak8CZgJ/ApYCrwLJAuIC+gIUAysDVgBwAIkAoQC3ANEA6QD/
ABYBLAFCAVwBcwGJAaIBtwHNAeEB+QENAiMCOgJIAl8CeQKQAqkCxALcAvQCDgMlA1MAawCFAJwAswDMAOQA+gAQASYBPAFWAW0B
gwGcAbABywHfAfcBCwIgAjgCTAJcAnQCiwKjAr4C1gLuAggDHwNSAGkAgwCaALEAygDiAPgAEgEnAT8BVwFuAYUBnQGyAckB3wH2
AQoCIAI3AksCXAJzAosCpAK+AtYC7gIHAyADUQBpAIIAmQCwAMkA4QD3ABEBJgE+AVcBbgGEAZwBsQHIAd4B9QEJAh8CNgJLAlkC
cwKLAqMCvQLWAu4CCAMfA1UAbACGAJ0AtADNAOUA+wATASkBQAFZAXABhgGdAbMBywHhAfgBDQIjAjkCTgJdAnYCjgKmAsEC2QLx
AgsDIwNZAHEAigCiALgA0gDqAAABFwEsAUQBXAFzAYoBogG3Ac4B4wH7AQ8CJQI8AlECYQJ5ApECqQLDAtwC9AINAyUDXABzAI0A
pAC7ANUA7QADAR0BMgFKAWIBeQGQAacBvQHRAecB/gETAikCQAJVAmUCfgKWAq4CyALhAvkCEgMqA2MAewCUAKwAwgDcAPQACgEk
AToBUgFqAYABmAGvAcUB2QHvAQYCGwIxAkgCXAJuAocCoAK3AtEC6wICAxsDNANrAIIAnAC0AMoA5AD7ABEBKAE/AVYBbwGFAZwB
swHJAeAB9gENAiICOAJPAl0CdgKPAqcCvwLZAvICCgMjAzsD3wHjAeYB6AHpAekB6AHoAecB5gHnAecB6AHoAekB6gHnAekB6wHt
Ae4B7gHtAewB7AHrAesB7AHtAe0B7gHvAfQB9QH3AfkB+gH6AfkB+QH4AfcB+AH4AfkB+gH6AfsBAgIEAgUCBwIIAggCBwIHAgYC
BgIGAgcCBwIIAggCCQIQAhICFAIVAhYCFgIVAhUCFAIUAhQCFQIVAhYCFgIXAhwCHgIgAiECIgIiAiECIAIfAh8CHwIgAiECIQIh
AiICIQIhAiMCJQIlAiUCJAIjAiICIgIiAiMCJAIkAiQCJQIdAh0CHwIgAiECIQIgAh8CHgIeAh4CHwIgAiACIAIhAg8CEAISAhQC
FQIVAhQCEwITAhMCEwIUAhQCFQIVAhYCAAICAgQCBgIHAgcCBgIFAgQCBAIEAgUCBgIGAgYCBwLxAfIB9AH2AfcB9wH2AfUB9gH2
AfYB9wH3AfgB+AH5AekB6QHsAe4B7wHuAe4B7QHsAewB7AHtAe0B7gHuAe8BCwIRAhgCHgIgAh4CGgITAgkC/wH2AfAB7wHxAfgB
AQIJAhACFwIdAh8CHgIZAhICCAL+AfUB7wHtAfAB9wEAAgYCDQIVAhsCHQIbAhcCEAIFAvsB8gHsAeoB7AH0Af0BAwIKAhMCGQIb
AhkCFQINAgMC+AHuAegB5gHpAfEB+wECAgkCEgIYAhoCGAITAgwCAQL2AewB5QHjAeYB7wH5AQMCCgISAhgCGwIYAhMCCwIAAvQB
6gHkAeEB5AHtAfgBBQILAhMCGQIbAhgCEwILAgAC9AHqAeMB4QHkAe0B9wEFAgsCEwIYAhoCGAITAgsCAAL0AeoB4wHhAeQB7QH3
AQMCCQISAhgCGwIZAhICCwIAAvUB6wHlAeMB5QHuAfgBAwIKAhICGQIcAhoCFAINAgIC9wHuAegB5gHoAfEB+gEHAg0CFQIbAh4C
HAIWAg8CBQL6AfEB6wHqAewB9AH9AQkCDwIXAh0CIAIeAhgCEQIHAv0B9AHuAe0B7wH3Af8BlQCrAMUA3AD0AA4BJgE8AVUBawGD
AZ0BswHJAeEB9gEOAiICOwJQAmUCfwKWAq0CxgLcAvQCDgMkAzoDUgNpA5gArwDIAN8A9gARASgBPwFYAW8BhgGfAbYBzAHlAfkB
EQImAj4CVAJoAoICmgKxAsoC4QL4AhEDKAM+A1cDbAOYAK8AyADfAPYAEQEoAT8BWAFuAYUBnwG2AcsB5AH4ARACJQI9AlICZwKC
ApkCsALKAuAC9wIRAycDPQNVA2wDlwCtAMUA3QD1AA4BJgE9AVUBbAGEAZwBswHKAeEB9gEMAiECOQJPAmMCfQKVAqwCxQLcAvMC
DQMjAzkDUgNoA5EAqADAANgA8AAKASIBOAFRAWcBfwGYAa4BxQHcAfEBBwIcAjQCSQJeAngCkAKnAsAC1wLuAggDHgM0A0wDYwOK
AJ8AuADQAOgAAgEaATEBSQFgAXcBkAGnAb0B1QHpAQECFQItAkMCWAJxAooCoAK5AtAC5wIBAxcDLQNGA1wDfgCVAK4AxgDeAPgA
EAEnAUABVwFuAYcBngGzAcwB4AH3AQ0CJAI5Ak8CaAJ/ApYCsALHAt4C+AIOAyQDPANSA3EAiQCjALwA0wDuAAcBHgE2AU0BZAF+
AZQBqgHDAdcB7QEBAhkCLwJEAlwCdQKMAqQCuwLSAuwCAwMYAzEDRwNZAHoAlgCvAMgA4wD8ABMBKwFCAVoBdAGKAaABuAHNAeMB
+AEPAiUCOgJSAmkCgQKaArECyALhAvgCDgMnAzwDVgBhAIgAogC7ANcA8QAJASEBOAFPAWkBgAGWAa4BwgHaAe4BBQIbAjECSQJg
AncCjwKmAr4C1wLuAgQDHAMxA1MAWwB4AJUAsADMAOYA/gAXAS4BRgFfAXUBjAGkAbkB0AHkAfwBEgIoAkACVgJtAoYCnAK0As0C
5AL6AhIDJwNRAFkAawCPAKkAxgDgAPgAEQEoAUABWgFwAYYBnwGzAckB3QH1AQoCIAI5Ak4CZQJ/ApUCrALGAtwC8gIKAyADTgBW
AF8AiACjAMAA2gDyAAoBIAE4AVIBaAF+AZcBqwHFAdkB8QEGAhwCNQJLAmECeAKOAqUCvwLUAusCAwMaA0wAVABgAIYAoAC9ANcA
7wAKASABOQFSAWgBfwGXAasBwgHXAe8BBAIbAjMCSQJfAnYCjQKkAr0C1ALqAgIDGQNKAFMAaACHAKAAvADWAO4ACQEfATgBUQFn
AX4BlgGqAcEB1gHtAQICGQIxAkgCXAJ2AowCpAK8AtMC6QIBAxgDSwBUAHIAjQClAMEA2gDyAAsBIgE6AVMBaQGAAZcBrAHEAdkB
8QEGAh0CNQJLAmACeAKQAqcCwALXAuwCBQMcA0sAWgB4AJAAqQDEAN0A9QANASUBPQFWAW0BgwGZAa8BxwHdAfMBCQIgAjgCTgJj
AnwCkwKrAsMC2gLwAggDIANOAGcAgQCaALMAzQDmAP4AFgEtAUYBXgF0AYwBogG4Ac4B5AH7ARECKAI/AlUCawKBApgCrwLIAt8C
9QINAyUDUwBxAIoAoQC8ANYA7QAGAR4BNQFOAWYBfAGUAakBwAHUAesBAQIYAi4CRQJbAnICigKjArkC0gLpAv8CFwMvA18AegCS
AKsAxgDeAPYADwEmAT4BVgFuAYUBnAGyAckB3AHzAQkCIAI3Ak0CYgJ6ApUCrQLEAtwC8wIJAyEDOQNpAIMAmwCzAM0A5wD+ABcB
LgFHAV8BdgGNAaQBuwHSAeYB/AESAikCQAJWAmsCgwKdArUCzALkAvsCEgMpA0EDcwCNAKQAvgDXAO8ACAEgATcBUAFoAX8BlgGt
AcQB2wHwAQYCHAIzAkoCYAJ2Ao4CpgK9AtUC7AIEAxoDMgNKA34AlwCtAMgA4QD4ABEBKAFAAVkBcQGIAaABtQHNAeMB+gEPAiYC
PgJUAmgCgAKYArACyALfAvcCDgMlAz0DVAOHAJ8AtgDQAOkAAAEZAS8BSAFhAXgBkAGnAb0B1QHrAQMCGAIvAkcCXQJxAooCogK2
As4C5QL8AhQDKgNCA1oD6wHsAewB6wHqAekB6QHpAekB6gHqAesB7AHtAe8B8AH3AfgB+AH3AfYB9gH1AfUB9gH2AfcB9wH4AfkB
+wH8AQUCBgIGAgYCBQIEAgMCBAIEAgUCBQIGAgYCBwIJAgoCFgIWAhUCFQIUAhMCEgISAhMCFAIUAhQCFQIWAhcCGQImAiQCIQIg
Ah4CHQIdAh0CHgIeAh8CHwIgAiACIgIkAigCLAInAiUCIwIiAiECIgIiAiMCIwIkAiQCJQImAigCHwIoAiMCIAIfAh4CHQIdAh4C
HwIgAiACIAIhAiMCJQIWAhoCFwIWAhQCEwITAhMCEwIUAhUCFQIVAhYCGAIZAggCCAIHAgYCBQIEAgQCBAIEAgUCBgIGAgUCBgII
AgkC+gH5AfkB+AH3AfYB9gH2AfYB9wH4AfgB9wH4AfkB+wHtAe4B7gHtAewB6wHrAesB6wHsAewB7QHvAfAB8gHzAeoB6wHrAeoB
6gHpAegB6AHoAekB6gHqAeoB6wHtAe8BHAIeAh4CGwIVAgwCAwL5AfEB7AHtAfIB+wEFAhACGQIZAhwCHAIZAhICCgIAAvUB7gHp
AekB7gH4AQMCDgIXAhcCGgIaAhcCEAIHAv0B8gHqAeUB5QHrAfQBAAILAhUCGAIaAhkCFQIOAgUC+gHvAecB4QHiAegB8gH+AQoC
FAIgAh4CGgIWAg4CBAL5Ae4B5QHfAeAB5gHwAfwBCQITAhsCIgIcAhYCDgIEAvkB7QHkAd8B3wHlAfAB/AEJAhMCFQIjAhsCFgIP
AgUC+QHtAeQB3wHfAeUB8AH8AQkCEwIVAhwCGQIVAg8CBQL5Ae4B5gHgAeEB5wHxAf0BCQITAhcCGgIZAhYCEAIHAvwB8QHoAeMB
4wHqAfQB/wEMAhQCGgIbAhsCGAISAgkC/wH0AewB5wHnAe4B+AECAg4CFgIcAh4CHgIaAhUCDAIBAvcB7wHqAesB8QH6AQQCEAIY
AhwCHgIeAhsCFQINAgIC+AHwAewB7AHyAfsBBgISAhkC
"""
}
